name: Update WoW Globals Luacheck

on:
  schedule:
    # 12:00 PM PST (20:00 UTC) every Tuesday
    - cron: '0 20 * * 2'
  workflow_dispatch:

jobs:
  update-luacheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run globals update script
        run: python scripts/generate_wow_globals.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .luacheckrc
          git diff --cached --quiet || git commit -m "chore: update WoW globals list"
          git push
